config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tours do
    resources :bookings, only: %i[create new]
  end
  resources :bookings, only: %i[index show edit destroy update] do
    resources :companions, only: %i[create]
    resources :reviews, only: %i[create]

  end
  # get '/users/:id/bookings', to: 'bookings#mybookings', as: 'mybookings'

  resources :agencies do
    resources :tours
    member do
      get :my_tours
    end
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :tour
  has_many :reviews
  has_many :companions
  validates :start_date, presence: true
  validates :quantity, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @tour = Tour.find(params[:tour_id])
  end

  def create
    # @tour = Tour.find(params[:tour_id])
    @tour = Tour.find(params[:tour_id])
    @booking = Booking.new(find_params)
    @booking.user = current_user
    @booking.tour = Tour.find(params[:tour_id])

    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  # /bookings/

  # solo dejar ingrsar a esas vistas un usario logeado


  def index
    @bookings = current_user.bookings
  end

  def show
    @bookings = Booking.find(params[:id])
    @companion = Companion.new
    @review = Review.new
    @companions = Companion.where(booking_id: @bookings.id)

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Post id: #{@bookings.id}", template: "bookings/show.html.erb", layout: "pdf"   # Excluding ".pdf" extension.
      end
    end
  end


  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(find_params)
    if @booking.save
      redirect_to booking_path(@booking), notice: "El booking ha sido modificado"
    else
      render :edit
    end
  end

  def destroy
    @bookings = Booking.find(params[:id])
    @bookings.destroy
    redirect_to bookings_path
  end



  private

  def find_params
    params.require(:booking).permit(
      :start_date,
      :quantity
    )
  end
end

app/views/bookings/edit.html.erb
<div class="container">
  <div class=""><img class="card-img-top mb-5 mb-md-0" src="https://blogs.incarail.com/hubfs/Imported_Blog_Media/CuscoRainBlog-1.png" alt="..." /></div>
    <%= simple_form_for @booking do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <%= f.input :start_date,label: 'Fecha a reservar', placeholder: '22/10/2010' %>
    <%= f.input :quantity,label: 'Cantidad de reservas', placeholder: '1' %>
    <%= f.button :submit ,'Reservar ahora', class: "btn btn-success p-3 w-100 rounded" %>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div class="jumbotron p-4 p-md-5 text-white rounded bg-dark" style= "background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(https://images.unsplash.com/photo-1528832095909-2f2436122ce6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1200&q=10)">
  <div class="col-md-12 px-0 p-5 card__header">
    <h1 class="display-2 font-italic">Mi lado viajero</h1>
    <br>
    <h2 class="my-3 text-white font-weight-bold">"Un viaje se vive 3 veces: Cuando lo soñamos, cuando lo vivimos y cuando lo recordamos"</h2>
    <br>
    <h2 class="mb-0 text-white font-weight-bold ">Invertir en viajar es invertir en uno mismo...</h2>
  </div>
</div>


<div class="row p-4 contenedor-booking" style="min-height:calc(100vh - 353px - 215px - 30px); box-sizing:border-box;">
  <% @bookings.each do |booking| %>
    <div class="contenedor-booking col-10 py-5">
        <div class="card d-flex justify-content-center p-2 card-booking w-100" style="height: 350px;">
          <div class="row d-flex justify-content-center">
            <div class="col-md-4">
              <%= cl_image_tag booking.tour.photos.first.key, height: 280, width: 400, crop: :fill,class:"img-fluid" %>
            </div>
            <div class="col-md-6">
                    <div class = "d-flex justify-content-left">
                    <div class="flex">
                    <div class="text-left">
                        <h1 class = "m-3"><strong> <%= booking.tour.title_tour %> </strong></h1>
                        <p class="price m-3" style="font-size:18px;"> Precio por persona: <strong>S/ <%= booking.tour.price %></strong></p>
                        <p class="side-note m-3" style="font-size:18px;">Experiencia para: <strong><%= booking.quantity %> persona(s)</strong></p>
                        <p class= "m-3" style="font-size:18px;">Fecha del tour: <%= booking.start_date %></p>
                        <div class="reviews m-3" style="font-size:18px;">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <span class="amount"> <%= booking.tour.reviews.count %> reviews </span>
                        </div>
                    </div>
                        <%= link_to "Ver Más", booking_path(booking), :class => "btn btn-lg",style:"font-size:18px;" %>
                    </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<%# aca tiene que ir las reservacion a realizar! %>
<body class="bg-light">
  <div class="container">
    <br>
      <div class="py-2 text-center">
        <h2>FORMULARIO DE PAGO</h2>
      </div>

    <br>

    <div class="row">
        <div class="card mb-3 col-12">
          <div class="row no-gutters">
            <div class="col-md-4">
              <%= cl_image_tag @tour.photos[0].key, height: 300, width: 400, crop: :fill,class: 'gallery__img',alt: "Gallery image 1" %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title text-center"><strong><%= @tour.title_tour %></strong></h5>
                <p class="card-text ml-2" style="font-size: 14px;"><%= @tour.description %></p>
                <p class="card-text ml-2 text-left text-muted" style="font-size: 14px;">Empresa: <%= @tour.agency.name %></p>
              </div>
            </div>
          </div>
        </div>
    </div>

    <div class="row">
      <div class="col-md-12 order-md-2 mb-4">
        <div class="tucartera">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="card-text text-center text-muted">Tu cartera</span>
          </h4>
          <ul class="list-group mb-3">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Costo Unitario:</h6>
                <small class="text-muted">Precio del tour por persona</small>
              </div>
              <span class="text-muted d-flex align-items-center" id="PrecioUnitario"><%= @tour.price %></span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Cantidad de Viajeros</h6>
                <small class="text-muted" >Personas que viviran la experiencia</small>
              </div>
              <span class="text-muted d-flex align-items-center cant-traveres" id="Cantidad-Personas"> </span>
            </li>
            <li class="list-group-item d-flex justify-content-between bg-light" >
              <div class="text-success">
                <h6 class="my-0">Cupon de Descuento</h6>
                <small>FLASHCARD2022</small>
              </div>
              <span class="text-success d-flex align-items-center">-<%= desc = 10.00 %></span>
            </li>
            <li class="list-group-item d-flex justify-content-between mt-2">
              <span>Total S/</span>
              <strong id="Totalbooking"></strong>
            </li>
          </ul>
        </div>

        <div class="card-payment-booking col-12 border p-3">
          <form> <span id="card-header" style="font-size:18px;">Saved cards:</span>
            <div class="row row-1" id="savedCards">
                <div class="col-2"><img class="img-fluid" src="https://img.icons8.com/color/48/000000/visa.png" /></div>
                <div class="col-7"> <input type="text" placeholder="**** **** **** 4296" style="font-size:18px;"> </div>
                <div class="col-3 d-flex justify-content-center"> <a href="#" style="font-size:18px;">Remove card</a> </div>
            </div>
            <span id="card-header" style="font-size:18px;">Add new card:</span>
            <div class="row-2 ml-4 mt-3">
                <div class="row row-2"> <span id="card-inner" style="font-size:15px;">Card holder name</span> </div>
                <div class="row row-2"> <input type="text" placeholder="Bojan Viner" style="font-size:18px;"> </div>
            </div>
            <div class="row three">
                <div class="col-7">
                    <div class="row-1 ml-4" id="cardNumber">
                        <div class="row row-2"> <span id="card-inner" style="font-size:15px;">Card number</span> </div>
                        <div class="row row-2"> <input type="text" placeholder="5134-5264-4" style="font-size:18px;"> </div>
                    </div>
                </div>
                <div class="col-2" id="expDate"> <input type="text" placeholder="Exp. date" style="font-size:18px;"> </div>
                <div class="col-2" id="cvv"> <input type="text" placeholder="CVV" style="font-size:18px;"> </div>
            </div>
          </form>
        </div>

          <%= simple_form_for [@tour, @booking] do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
            <%= f.input :start_date,label: 'Fecha a reservar', placeholder: '22/10/2010' %>
            <%= f.input :quantity,label: 'Cantidad de reservas', placeholder: '1' %>
            <%= f.button :submit ,'Reservar ahora', class: "btn btn-success p-3 w-100 rounded", style:"font-size:3rem;" %>
          <% end %>

        <h5>(*)Recuerda que tienes que completar la informacion de tus acompañantes</h5>
      </div>
    </div>

    <script>
      const cantidadPersonas = document.getElementById("Cantidad-Personas")
      // PrecioTotal.innerHTML = "hola";
      // document.addEventListener("click",CalcularDias)
      const inputPersonas  = document.getElementById('booking_quantity')
      const Total = document.getElementById('Totalbooking')
      let precio = document.getElementById('PrecioUnitario')
          inputPersonas.addEventListener("change", (event) => {
          const cantidad = inputPersonas.value;
          cantidadPersonas.innerHTML =`${cantidad} `
          console.log(cantidad)
          Total.innerHTML= cantidad*precio.innerText - 10;

        })


    </script>



    </div>

  </div>
</body>

app/views/bookings/show.html.erb
<section class="py-5 show-booking">
  <div class="container px-4 px-lg-5 my-5 ">
      <div class="row gx-4 gx-lg-5 align-items-center data ">
          <div class="col-md-6"><%= cl_image_tag @bookings.tour.photos.first.key, height: 280, width: 400, crop: :fill,class:"img-fluid" %></div>
          <div class="col-md-6">
              <h1 class="mb-4 text-center title" style="font-size:30px;"><%= @bookings.tour.title_tour %></h1>
              <div class="fs-5 mb-4">
                  <h4 class="text-decoration-line-through" style="font-size:18px;">Precio: S/<%= @bookings.tour.price %></h4>
              </div>
              <div class="fs-5 mb-4">
                  <h4 class="text-decoration-line-through" style="font-size:18px;">Fecha-salida: <%= @bookings.start_date %></h4>              </div>
              <div class="fs-5 mb-4">
                <h4 class="text-decoration-line-through" style="font-size:18px;">Fecha-regreso: <%= @bookings.start_date %></h4>
              </div>
              <div class="fs-5 mb-4">
                <h4 class="text-decoration-line-through" style="font-size:18px;">Tiempo de tour: <%= @bookings.tour.duration %></h4>
              </div>
              <div class="fs-5 mb-4">
                  <h4 class="text-decoration-line-through" style="font-size:18px;">Acompañantes: <%= @bookings.quantity %> persona(s)</h4>
              </div>
              <div class="d-flex justify-content-around link-path">
                  <%= link_to 'Editar', edit_booking_path, class: "btn btn-secondary py-3 px-5",style:"font-size:15px;"%>
                  <%= link_to 'Eliminar', booking_path(@bookings), class: "btn btn-secondary py-3 px-5",style:"font-size:15px;", method: :delete, data: {confirm: "Seguro?"}%>
              </div>
          </div>
      </div>
  </div>

  <div class="container ">
      <div class="accordion mt-4 data" id="accordionExample">
        <div class="card w-100">
          <div class="card-header w-100" id="headingOne">
            <h2 class="mb-0">
              <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                <p style="font-size:2rem;">Tus Acompañantes:</p>
              </button>
            </h2>
          </div>

          <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
            <div class="card-body">
              <%cantidad =@bookings.quantity %>
              <% actual_companion = Companion.where(booking_id: @bookings.id).count %>
              <%# INICIO formularios para CREAR acompañantes %>
              <%(cantidad-actual_companion ).times do%>
              <div class="container-fluid d-flex row mt-3 companions-create">
                <%= simple_form_for(@companion, url: booking_companions_path(@bookings)) do |f| %>
                  <%= f.error_notification %>
                  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
                  <%= f.input :first_name,label: 'Primer nombre', placeholder: 'Ana' %>
                  <%= f.input :last_name,label: 'Apellido', placeholder: 'Marcela' %>
                  <%= f.input :age,label: 'Edad', placeholder: '20' %>
                  <%= f.input :document_number,label: 'Documento de Identidad', placeholder: '70321459' %>
                  <%= f.button :submit ,"Confirmar",class:"btn-success ml-1 m-5", style:"font-size:15px;" %>
                  <% end %>
              </div>
              <%end%>
              <%# FIN formularios para CREAR acompañantes %>

              <%# formularios para VER acompañantes %>
              <p style="font-size:1.9rem;" class="mt-3">Acompañantes registrados:</p>
              <% @companions.each do |acompanante|%>
                <div class="container-fluid mt-3">
                  <div class="d-flex justify-content-around">
                    <div style="font-size:17px"><label for="">Nombre</label><p> <%=acompanante.first_name%> </p></div>
                    <div style="font-size:17px"><label for="">Apellido</label><p> <%=acompanante.last_name%> </p></div>
                    <div style="font-size:17px"><label for="">Edad</label><p> <%=acompanante.age%> </p></div>
                    <div style="font-size:17px"><label for="">DNI</label><p> <%=acompanante.document_number%> </p></div>
                  </div>
                </div>
              <%end%>
              <%# formularios para VER acompañantes %>
            </div>
          </div>
        </div>
        <div class="card w-100 link-path">
          <div class="card-header" id="headingTwo">
            <h2 class="mb-0">
              <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                <p style="font-size:2rem;">Tu review</p>
              </button>
            </h2>
          </div>
          <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
            <div class="card-body">
               <div class="container-fluid d-flex row row mt-3">
                <%= simple_form_for(@review, url: booking_reviews_path(@bookings)) do |f| %>
                      <%= f.error_notification %>
                      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
                      <div class="col">
                        <%= f.input :content,label: 'Comentario', placeholder: 'Una bonita experiencia, lo recomendaria' %>
                      </div>
                      <div class="col">
                        <%= f.input :rating,label: 'Calificación ', placeholder: '1-5' %>
                      </div>
                       <%= f.input :photos,label: 'Fotos', as: :file, input_html: { multiple: true } %>
                      <%= f.button :submit ,"Enviar Review", class: "btn-success ml-4", style:"font-size:15px;" %>
                      <% end %>
              </div>
            </div>
          </div>
        </div>

      </div>
    <%# fin ACORDEON %>
  </div>
  <div class="container text-center link-path">
    <%= link_to 'Regresar', bookings_path, :class => "btn btn-secondary py-3 px-5 mt-3",style:"font-size:15px;" %>
    <%= link_to "Imprimir", booking_path(@bookings, format: :pdf), :class => "btn btn-secondary py-3 px-5 mt-3",style:"font-size:15px;" %>
  </div>
</section>