config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tours do
    resources :bookings, only: %i[create new]
  end
  resources :bookings, only: %i[index show edit destroy update] do
    resources :companions, only: %i[create]
    resources :reviews, only: %i[create]

  end
  # get '/users/:id/bookings', to: 'bookings#mybookings', as: 'mybookings'

  resources :agencies do
    resources :tours
    member do
      get :my_tours
    end
  end
end

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |type, msg| %>
    <div class="modal fade show" id="exampleModal" style="display:block;" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= msg %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<!-- <div class="footer container-fluid w-100 pb-4 pt-4  mt-5"> -->
<div class="container-fluid mt-5 mb-5">
    <div class="card position-absolute" id ="card-footer">
        <div class="row mb-4 ">
            <div class="col-md-4 col-sm-11 col-xs-11">
                <div class="footer-text pull-left">
                    <div class="d-flex">
                        <%# <h1 class="font-weight-bold mr-2 px-3" style="color:#16151a; background-color:#957bda"> Q </h1> %>
                        <h1 style="color: #186B6D">Explora</h1>
                    </div>
                    <h5 class="card-text">Somos una empresa que brinda las mejores experiencias de viajes, conectando agencias con turistas.</h5>
                    <div class="social mt-2 mb-3"> <i class="fa fa-facebook-official fa-lg"></i> <i class="fa fa-instagram fa-lg"></i> <i class="fa fa-twitter fa-lg"></i> <i class="fa fa-linkedin-square fa-lg"></i> <i class="fa fa-facebook"></i> </div>
                </div>
            </div>
            <div class="col-md-2 col-sm-1 col-xs-1 mb-2"></div>
            <div class="col-md-2 col-sm-4 col-xs-4">
                <h5 class="heading">Servicios</h5>
                <ul>
                    <li>Conviertete en afiliado</li>
                    <li>Vive nuevas experiencias</li>
                </ul>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-4">
                <h5 class="heading">Empresas</h5>
                <ul class="card-text">
                    <li>Agencias de viaje</li>
                    <li>Museos</li>
                </ul>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-4">
                <h5 class="heading">Compañia</h5>
                <ul class="card-text">
                    <li>Acerca de</li>
                    <li>Contacto</li>
                </ul>
            </div>
        </div>
        <div class="divider mb-4"> </div>
        <div class="row" style="font-size:10px;">
            <div class="col-md-6 col-sm-6 col-xs-6">
            </div>
        </div>
    </div>
</div>



<%# <div class="container-fluid w-100 pb-4 pt-4  mt-5 footer">

  <div class="row social-media justify-content-center ">
    <a href=""><i class="fa fa-facebook" aria-hidden="true"></i></a>
    <a href=""><i class="fa fa-twitter" aria-hidden="true"></i></a>
    <a href=""><i class="fa fa-youtube-play" aria-hidden="true"></i></a>
    <a href=""><i class="fa fa-instagram" aria-hidden="true"></i></a>
    <a href=""><i class="fa fa-whatsapp" aria-hidden="true"></i></a>
    <a href=""><i class="fa fa-pinterest-p" aria-hidden="true"></i></a>
  </div> %>


  <%# <div class="row justify-content-around m-3 link-footer "> %>
     <%# <%= link_to "Centro de Ayuda",'',  class: "nav-link" %>
     <%# <%= link_to "Políticas de Privacodad",'', class: "nav-link" %>
     <%# <%= link_to "Nosotros",'', class: "nav-link" %>
     <%# <%= link_to "Agencias de Viajes",'', class: "nav-link" %>
     <%# <%= link_to "Afilitiate a nosotros ",'', class: "nav-link" %>
  <%# </div> %>
  <%# <div class="row justify-content-around m-3">
    <%= link_to "Terminos y condiciones",'', class: "nav-link" %>
     <%# <%= link_to "A© 1997-2022 Explora, Inc.",'', class: "nav-link" %>
  <%# </div> %>
<%# </div> %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon pl-5 pr-5 pb-0 mb-3">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "EXPLORA.png" %>
  <% end %>

  <% if user_signed_in? %>
    <p class="mb-0" style="font-size:2rem;"> Hola,
      <%= current_user.first_name.capitalize%>!
    </p>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse " id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Reserva Ahora!", tours_path, class: "nav-link booking-noow", style: "background-color:#186B6D; color: #fff !important; border-radius:4px;" ,id:"booking-now" %>
      </li>
    <%# Agregarun if que verifique que scurrent_user existe current_user.present? %>
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Mis Reservas", bookings_path , class: "nav-link" %>
        </li>
          <% if current_user.agency %>
            <li>
             <%= link_to "Mi agencia", agency_path(current_user.agency), class:  "nav-link" %>
            </li>
             <% else %>
            <li class="nav-item active">
              <%= link_to "Afiliate a nosotros", new_agency_path , class: "nav-link" %>
            </li>
          <% end %>
        <li class="nav-item dropdown">
            <% if current_user.photo.attached?%>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
            <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8JyScJ3XAm0g9mNMQ1Ws7EI6LoVgs7_HDXg&usqp=CAU", class: "avatar dropdown-toggle""navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

            <%end%>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Cambiar Contraseña", "#", class: "dropdown-item" %>
              <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>

</div>