config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tours do
    resources :bookings, only: %i[create new]
  end
  resources :bookings, only: %i[index show edit destroy update] do
    resources :companions, only: %i[create]
    resources :reviews, only: %i[create]

  end
  # get '/users/:id/bookings', to: 'bookings#mybookings', as: 'mybookings'

  resources :agencies do
    resources :tours
    member do
      get :my_tours
    end
  end
end

app/models/agency.rb
class Agency < ApplicationRecord
  belongs_to :user
  has_many :tours
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :tax_number, presence: true, uniqueness: true
  validates :state, presence: true
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  def show
    @agency = Agency.find(params[:id])
    @tours = Tour.where(agency_id: @agency.id)

  end

  def new
    @agency = Agency.new
  end

  def create
    @agency = Agency.new(find_params)
    @agency.user = current_user

    if @agency.save
      redirect_to agency_path(@agency)
    else
      render :new
    end
  end

  def edit
    @agency = Agency.find(params[:id])
    # authorize @car
  end

  def update
    @agency = Agency.find(params[:id])
    # authorize @car
    @agency.update(find_params)
    if @agency.save
      redirect_to agency_path(@agency)
    else
      render :edit
    end
  end

  def my_tours
    @agency = Agency.find(params[:id])
    @tours = Tour.where(agency_id: @agency.id)
  end

  private

  def find_params
    params.require(:agency).permit(
      :name,
      :email,
      :tax_number,
      :address,
      :state,
      :id,
      :latitude,
      :longitude
    )
  end
end

app/views/agencies/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Actualizar datos de tu agencia </h3>
        <%= simple_form_for(@agency) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
          <%= f.input :name, placeholder: 'Nombre' %>
          <%= f.input :email, placeholder: 'email' %>
          <%= f.input :tax_number, placeholder: 'R.U.C' %>
          <%= f.input :address, placeholder: 'Dirección' %>
          <%= f.input :state, placeholder: 'Provincia' %>
          <%# <%= f.input :latitude, placeholder: 'latitude' %>
          <%# <%= f.input :longitude, placeholder: 'longitude' %>
          <%= f.button :submit,'Editar agencia', class: "btn btn-success p-3 w-100 rounded",style:"font-size:18px;"  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/agencies/my_tours.html.erb
<div class="row m-3 d-flex justify-content-center">
  <div class="col-md-11">
    <div class="container tour-index">
      <div class="d-flex justify-content-between">
        <h2 style="font-size:30px;">Mis tours ofrecidos</h2>
        <%= link_to "Añadir tour",new_agency_tour_path(@agency), :class => "btn btn-success py-3 px-5",:style => "font-size:14px;"%>
      </div>
      <%= render "shared/flash" %>
      <% @tours.each do |tour| %>
        <div class="row card-tour mt-4 pt-5 pb-5">
          <div class="col-md-3 d-flex justify-content-center align-items-center ">
            <% tour.photos.each do |photo| %>
              <%= cl_image_tag photo.key,:style => "width:100%;" ,class:"img-fluid" %>
              <%break%>
            <% end %>
          </div>

          <div class="col-md-4">
          <h3 class = "tours-card-title"><%=tour.title_tour%> </h3>
          <p class="tours-card-content-p"><%=tour.description%>  </p>
          <p class="tours-card-content"><i class="far fa-clock" style="color: #D1D1D1"></i> Duración: <%=tour.duration %> </p>
          <p class="tours-card-content">Brindado por: <span class="tours-agency-name"> <%=tour.agency.name%> </span></p>
          <%# <p>geocoding: <%=tour.agency.latitude%0 </p>%>
          </div>

          <div class="col-md-4 pt-5 align-items-center" style="text-align:center;">
            <p><span style="font-size:1.5rem; font-weight: 700;"> S/ <%= tour.price%> </> </p>
            <div class="d-flex justify-content-between">
              <%= link_to "Ver más",tour_path(tour), :class => "btn btn-success py-3 px-5",:style => "font-size:14px;"%>
              <%= link_to "Editar",edit_agency_tour_path(agency_id:tour.agency.id,id:tour.id), :class => "btn btn-success py-3 px-5",:style => "font-size:14px;"%>
              <%= link_to "Eliminar",tour_path(tour),method: :delete, data: { confirm: "Estas seguro?" }, :class => "btn btn-success py-3 px-5",:style => "font-size:14px;" %>
              <%# <%= link_to 'Eliminar', tour_path(tour), method: :delete, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary btn-lg'}
              <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content"></div>
                </div>
              </div> %>
              <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Tenga en cuanta que: </h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                      </button>
                    </div>
                    <div class="modal-body">
                      No se puede eliminar porque ya tiene reservas
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <button type="button" class="btn btn-primary">Save changes</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/agencies/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Estas a punto de crear tu agencia </h3>
        <%= simple_form_for(@agency) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
          <%= f.input :name, placeholder: 'Nombre' %>
          <%= f.input :email, placeholder: 'email' %>
          <%= f.input :tax_number, placeholder: 'R.U.C' %>
          <%= f.input :address, placeholder: 'Dirección' %>
          <%= f.input :state, placeholder: 'Provincia' %>
          <%# <%= f.input :latitude, placeholder: 'latitude' %>
          <%# <%= f.input :longitude, placeholder: 'longitude' %>
          <%= f.button :submit,'Crear agencia', class: "btn btn-success p-3 w-100 rounded",style:"font-size:18px;"  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/agencies/show.html.erb
<div class="container mb-5" style="">
  <div class="row mt-5">
    <div class="col-8 mt-5">
    <p style="font-size: 2.5rem;">
      Les damos la bienvenida <%=@agency.name%>
    </p>
    </div>
    <div class="col-4 d-flex align-items-center justify-content-center mt-5">
      <%= link_to "Editar mi perfil",  edit_agency_path , class: "btn btn-secondary py-3 px-5",style:"font-size:15px;" %>
      <%= link_to "Ver mis tours", my_tours_agency_path , class: "btn btn-secondary py-3 px-5 ml-2",style:"font-size:15px;" %>
    </div>
  </div>

  <br>

  <div class="d-flex justify-content-between" style="background-color: #f2f2f2;">
    <div class="col mt-5 p-3 d-flex flex-column align-items-center">
      <h2 style="font-size: 28px;">Datos de la empresa: </h2>
      <div><h2>Direccion: <%=@agency.address%></h2></div>
      <div><h2>Correo: <%=@agency.email%></h2></div>
      <div><h2>Localidad: <%=@agency.state%></h2></div>
      <div><h2>RUC: <%=@agency.tax_number%></h2></div>
    </div>
    <div class="col"><img class="agency-img" src="https://www.golden-expeditions.com/slider1/baner2.jpg" style="width:100%;" alt=""></div>
  </div>
  <div class="create-tour-card mt-2" style="background-color: #f2f2f2; ">
    <div class="row justify-content-center p-3">
      <p class="title-card-tour-create" style="font-size:3rem">Empiece a crear productos y ampliar su negocio</p>
    </div>
    <div class="row pt-4 pb-4">
      <div class="col-2 d-flex align-items-center justify-content-center">
        <img src="http://imgfz.com/i/1iClTro.png" alt="">
      </div>
      <div class="col-8">
        <p class="first">
          1. ¡Cree su primer producto!
        </p>
        <p class="second">
          Añada excursiones, actividades y experiencias para que los viajeros las puedan reservar
        </p>
      </div>
      <div class="col-2 d-flex align-items-center justify-content-center">
      <%= link_to "Crear Tour", new_agency_tour_path(@agency), class: "btn btn-success",style:"font-size:15px;"%>
      </div>
    </div>
    <div class="row pt-4 pb-4">
      <div class="col-2 d-flex align-items-center justify-content-center">
        <img src="http://imgfz.com/i/j6NsUoR.png" alt="">
      </div>
      <div class="col-8">
        <p class="first">
          2. Indíquenos cómo quiere recibir los pagos
        </p>
        <p class="second">
          Seleccione una moneda y añada su información bancaria
        </p>
      </div>
      <div class="col-2 d-flex align-items-center justify-content-center">
        <%= link_to "Configurar", '', class: "btn btn-dark",style:"font-size:15px;" %>
      </div>
    </div>
  </div>
</div>